### ISSUE TITLE
Code completions are flaky with atom-languageclient 0.8.0

### ISSUE THREAD

**Issue by daviwil** [daviwil/ide-powershell#2]
atom-languageclient 0.8.0 got support for using trigger characters to initiate code completions but it isn't working so smoothly with PSES.  Need to investigate whether it's a problem on our side or something in atom-languageclient.

**Comment by SeeminglyScience** [comment]
If we're thinking of the same issue it's acting, like it's using the `CompletionText` property on `CompletionResult` instead of `ListItemText`.   I can't find anything on our side that would cause that though.

**Comment by daviwil** [comment]
Ahhh, this has actually been fixed in atom-languageclient 0.8.1, so it can be closed.  Got an example of the wrong completion text being displayed?
